---
- name: server nginx
  hosts: all
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: yes
  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
