# -*- mode: ruby -*-
# vi: set ft=ruby :

# VARIABLES 
CPU = 1
RAM = 1024
# create a Vagrantfile with a synced folder and provision with Ansible
Vagrant.configure("2") do |config|
  # define the VM parameters
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "10.0.0.10"
  # create a synced local folder
  config.vm.synced_folder "./website", "/var/www/html"
  # customize the VirtualBox VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM
    vb.cpus = CPU
  end
  # provision the VM with Ansible
  config.vm.provision "ansible_local" do |ansible|
    # define the playbook
    ansible.playbook = "nginx.yaml"
    # install Ansible locally
    ansible.install = true
    ansible.install_mode = "pip"
    ansible.pip_install_cmd = "curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | sudo python"
  end
end
