# -*- mode: ruby -*-
# vi: set ft=ruby :

# VARIABLES 
CPU = 2
RAM = 2048
HOSTNAME = "srv-ansible"
# create a Vagrantfile with a synced folder and provision with Ansible
Vagrant.configure("2") do |config|
  # define the VM parameters
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = HOSTNAME
  config.vm.network "private_network", ip: "10.0.0.10"
  # customize the VirtualBox VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM
    vb.cpus = CPU
    vb.name = HOSTNAME
  end
  # provision the VM with script
  config.vm.provision "shell", path: "Install_ansible.sh"
end
