# -*- mode: ruby -*-
# vi: set ft=ruby :

# VARIABLES 
CPU = 2
RAM = 2048
IP = "192.168.56.10"
# create a Vagrantfile
Vagrant.configure("2") do |config|
  # use the geerlingguy/centos7 box
  config.vm.box = "geerlingguy/centos7"
  # Create a private network, using a specific IP
  config.vm.network "private_network", ip: IP
  # customize the VirtualBox VM
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = RAM
    vb.cpus = CPU
  end
  # provision the VM with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y nginx
    sudo systemctl start nginx
  SHELL
end
