# -*- mode: ruby -*-
# vi: set ft=ruby :
# VARIABLES 
CPU = 1
RAM = 1024
# create a Vagrantfile with a synced folder
Vagrant.configure("2") do |config|
  # use the ubuntu/xenial64 box
  config.vm.box = "ubuntu/xenial64"
  # Create a private network, using a specific IP
  config.vm.network "private_network", ip: "10.0.0.10"
  # create a synced local folder
  config.vm.synced_folder "./website", "/var/www/html"
  # customize the VirtualBox VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM
    vb.cpus = CPU
  end
  # provision the VM with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y nginx
    sudo systemctl start nginx
  SHELL
end
